//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefIntMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Report1
    {
        public int IDPoliza { get; set; }
        public string Tipo { get; set; }
        public string Modelo { get; set; }
        public int Año { get; set; }
        public string Color { get; set; }
        public string Placa { get; set; }
        public string Chasis { get; set; }
        public string NombreTP { get; set; }
    }
}
